spring:
  profiles: dev
  thymeleaf:
    cache: false

server:
  port: 8081
  url: http://localhost:8081
  env: desarrollo
  urlApi: http://localhost:8080/
  servlet:
    session:
      cookie:
        name: MYSESSIONID





email:
  server:
  email-dev: 8888

# Log Files
log:
  file:
    location: dev/file.log
    level: DEBUG
  env: dev

logging:
  level:
    org.springframework: ERROR
    ar.com.marete: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %X{sessionId} - %X{nombre} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log

